# Generated by Django 4.0.6 on 2022-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_shop_by_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_by_brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
