# Generated by Django 4.0.6 on 2022-08-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_alter_shop_by_brand1_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, max_length=200, null=True)),
                ('language_logo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
