# Generated by Django 4.0.6 on 2022-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
