# Generated by Django 4.0.6 on 2022-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0009_remove_shopping_bag_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('animated_text_description', models.TextField(blank=True, max_length=200, null=True)),
                ('small_animated_word', models.CharField(blank=True, max_length=200, null=True)),
                ('product_price', models.FloatField()),
                ('background_cover_image', models.ImageField(upload_to='media')),
                ('product_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
