# Generated by Django 4.0.6 on 2022-08-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0011_trending_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as1', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.shop_by_categories')),
            ],
        ),
    ]
