# Generated by Django 4.0.6 on 2022-08-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0012_mobile_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=200, null=True)),
                ('acessories_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.accessories')),
                ('brand_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.shop_by_brand1')),
                ('language_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.language')),
                ('mobile_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.shop_by_categories')),
                ('shopping_bag_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.shopping_bag_items')),
                ('slider_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.slider')),
                ('trending_items_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.trending_items')),
            ],
        ),
    ]
