# Generated by Django 4.0.6 on 2022-08-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0013_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.shop_by_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Categoryall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.categoryall')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='acessories_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='language_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mobile_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shopping_bag_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending_items_category',
        ),
        migrations.DeleteModel(
            name='Mobile_Phones',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
