# Generated by Django 4.0.6 on 2022-08-24 20:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0015_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trending_Items',
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='specification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
