# Generated by Django 4.0.6 on 2022-08-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0018_remove_product_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
