# Generated by Django 4.0.6 on 2022-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0021_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('area_code', models.CharField(max_length=200)),
                ('primary_phone', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
            ],
        ),
    ]
