# Generated by Django 4.0.6 on 2022-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0022_shipping_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_addres',
            name='bussiness_type',
            field=models.BooleanField(default=False),
        ),
    ]
