# Generated by Django 4.0.6 on 2022-09-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0023_shipping_addres_bussiness_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_addres',
            name='street_address_2',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
