# Generated by Django 4.0.6 on 2022-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0024_shipping_addres_street_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_addres',
            name='bussiness_type',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
