# Generated by Django 4.0.6 on 2022-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0025_alter_shipping_addres_bussiness_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=200)),
                ('cardnumber', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=200)),
                ('expiration_date_month', models.CharField(max_length=200)),
                ('expiration_date_year', models.CharField(max_length=200)),
                ('CSC_card', models.CharField(max_length=200)),
            ],
        ),
    ]
