# Generated by Django 4.0.6 on 2022-09-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0026_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.ImageField(default=False, upload_to='Payment_Type')),
            ],
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.payment_type'),
        ),
    ]
