# Generated by Django 4.0.6 on 2022-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0027_payment_type_alter_payment_method_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='payment_type',
            field=models.CharField(max_length=200),
        ),
    ]
